version: "3"
services:
  API:
    image: kiiiproekt
    ports:
      - "9090:9090"
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Alebaza42!
      MYSQL_DATABASE: mysql
